### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dermonito** [john-friedman/datamule-python#1]
Hello!
I get the follwoing error when trying to proceed with any action:
asyncio.run() cannot be called from a running event loop
![Screenshot 2024-09-13 121634](https://github.com/user-attachments/assets/6e0c3c32-a446-4c18-a001-2400babde07e)

**Comment by john-friedman** [comment]
Hmm. I think the error may be from running in a jupyter notebook. I'll take a look and update the package for jupyter compatibility.

**Comment by john-friedman** [comment]
Yep! It's a jupyter notebook issue. Jupyter notebooks already run an event loop, which conflicts with the asyncio.run().

To fix, you can use the nest_asyncio package.
```
import datamule as dm
import nest_asyncio
nest_asyncio.apply()

downloader = dm.Downloader()

downloader.download_using_api(form='10-K', ticker='AAPL')
```

Let me know if this works for you! I'll add native support for jupyter notebooks soon. @dermonito

**Comment by john-friedman** [comment]
The package has been updated. As of datamule .20, jupyter notebooks should be supported natively.

**Comment by dermonito** [comment]
Thank you, for some reason problem persists for me, but I cank work around it using 

import nest_asyncio
nest_asyncio.apply()

Thank you very much!

**Comment by john-friedman** [comment]
Have you updated your package? The current version is 0.22.

**Comment by dermonito** [comment]
Great, thank you! Now it does work for me.

**Comment by john-friedman** [comment]
Great! Let me know if you have any more issues.

**Comment by dermonito** [comment]
Unfortunately, I do have :(

Before the update I was able to download filings, but now they all seem to be damaged. Irregradless of what filing type or what company I use the resulting htm file says the following (2 examples for AAPL 10-Ks):

(1) "NoSuchKeyThe specified key does not exist.edgar/data/320193/0001193125134165/d590790d10k.htmP2JJV1HPH29Q5A3JaxLY3zlhGpzMUtf+nbGjAN9ikxmBAYpKRMNgcnFDl23dOceVduxUACLQX4Ca3rSsmQDQQsu8NAc="
(2) "NoSuchKeyThe specified key does not exist.edgar/data/320193/0001047469030416/a2124888z10-k.htmP2JH85VPY8962HH9eX4O3tLpb9I2FnLvXTt4/TAUEpH5Zz79ENan+q7L5WznVPxvmcFc2a4cmA+IGKLOsH5R5O6j4Vo="

Do you know what might be the problem here? Should I open a new issue for this?

**Comment by john-friedman** [comment]
Hey, I'm terribly sorry about that. I was setting up the database to update at faster intervals and I broke the database. I'm fixing it now.

Can you use the indexer.run() function instead? By default it downloads the indices now, which takes about 10-30 seconds.

**Comment by john-friedman** [comment]
```
from datamule import Indexer
indexer = Indexer()
indexer.run(download=True)
```

**Comment by dermonito** [comment]
Thank you very much, I can download files using the indexer function. I didn't understand though what you menat by "re-running takes about 20 minutes" in the documentation, should I re-run indexer function every 20 minutes or so?

There is anotehr problem with the package that I noticed, whenever I download xml files, thay are again seem to be damaged, and the number of files that the interface suggests was downloaded is in contradiction with only one xml fuile being downloaded. To see it, one could download form="D" for TESLA as an example.

**Comment by john-friedman** [comment]
Good point, I'll clarify the readme. You can either download the indices or run the indexer. Downloading takes about 10-30 seconds, while running the indexer takes about 30 minutes. However, the latter will have more recent filings.

Re: 

1.  Downloaded files being damaged, that's likely to be on the SEC side. They wrap their files with SGML which can be frustrating. Can you send me more details? I'll add a function to unwrap the SGML to the package.
2. The number of files the interface downloads is in contradiction: I'll look into this.

**Comment by john-friedman** [comment]
2. The files are downloading correctly. The issue is that they are overwriting each other. I'll modify this to save the file names as their accession number.

**Comment by john-friedman** [comment]
Just patched 2. Should be fixed in datamule v0.23

**Comment by dermonito** [comment]
1-2. Ok, great! So, basically, if we open one of the D Forms of tesla directly from the sec.gov, we get a nice https://www.sec.gov/Archives/edgar/data/1318605/000128825718000026/xslFormDX01/primary_doc.xml

Using the package though I get the follwoing doc primary_doc.xml : 
![image](https://github.com/user-attachments/assets/fdfb067f-22ca-46b9-aed0-7f708846c123)

**Comment by john-friedman** [comment]
Gotcha. This isn't a SGML issue as I first thought. What's going on is the downloader is grabbing the human readable document, not the one meant for a machine. Added a jupyter notebook [here](https://github.com/john-friedman/datamule-python/blob/main/examples/human_readable.ipynb) if you're interested in learning more.

Human:   https://www.sec.gov/Archives/edgar/data/1318605/000128825718000026/xslFormDX01/primary_doc.xml
Machine: https://www.sec.gov/Archives/edgar/data/1318605/000128825718000026/primary_doc.xml

I've set the default version in datamule v0.25 to download the machine version. You can toggle to human version using human_readable = True in download or download_using_api.

**Comment by john-friedman** [comment]
This still doesn't explain why when you open the file in browser vs from the downloaded package it renders differently. Are you using google chrome to open the document on the SEC website and another application to view the downloaded file?

My guess is the SEC filings is malformed (pretty typical). Browsers are designed to render imperfect html, while other applications are not.

**Comment by dermonito** [comment]
Hello, thank you for your help! So as to the XML filings problem:

For me using human_readable = True did not solve the problem:
download function doesn't recognize this parameter, while download_using_api does, but files are still in machine version. I tried several different browsers, and xml readers, chrome as well for both downloaded xmls and sec.gov xmls. The package version is also up to date 0.26

**Comment by dermonito** [comment]
I use anaconda, I reinstalled the package and now download() recognizes human_readable parameter.
Now when I toggle human_readable=True, I still get the same 
![image](https://github.com/user-attachments/assets/a58ec6d3-8f00-47c2-9158-0b802d9f3f70)

However, if I toggle human_readable=False, I get a nice version, even though not the same structure and design as in sec.gov, but for my purposes that is not a problem
![image](https://github.com/user-attachments/assets/973ff0fc-ab39-428e-871c-67b6babfc4c1)

**Comment by dermonito** [comment]
There is another problem I have encountered:
For a large number of companies the package cannot download any filings from SEC. My current hypothesis is that all these companies aren't public. But needs to be checked.

For example, Portal Software, its cik is 1080306 or 0001080306. 
When I try to:
_from datamule import Downloader
downloader = Downloader()
downloader.download_using_api(form='10-K',cik='1080306', output_dir='Portal Software' )_  

I get:
_Successfully downloaded 0 out of 0 URLs_

Even though on SEC (https://www.sec.gov/edgar/browse/?CIK=1080306) There are 6 10-K reports.

**Comment by john-friedman** [comment]
Huh that's weird. I'll look into it. (re: human readable)

For the companies the package can't download from, I'm hoping to fix that by tomorrow! Currently the package only downloads from companies which have tickers (about 7k).

I'm going to add you to the contributors.md as your feedback is very helpful.

**Comment by john-friedman** [comment]
Figured it out! The file is malformed on the SEC server side. Your browser adds the missing tags which is why it is not visible 

If you want to use the human readable filings, reading them into lxml first should fix it.
```
from lxml import etree

with open('filings/000131860509000005primary_doc.xml', 'r', encoding='utf-8') as file:
    html = etree.parse(file, etree.HTMLParser())
```

You can also change the filetype of the human readable files to .htm or .html and it'll work as expected.

**Comment by dermonito** [comment]
Great, thank you very much! Please let me know when you'll add package functionality for all companies.

**Comment by john-friedman** [comment]
@dermonito , should work now with v.301. Btw, I removed the human readable option due to change in API used. Let me know if you want it back.

```
import datamule as dm
downloader = dm.Downloader()
downloader.download(cik='1080306',form='10-K')
```

**Comment by dermonito** [comment]
@john-friedman it's great, thank you!
For some reason now the output_dir parameter is missing from download(), and one cannot actually download the filing, rather only get the link. Was that something intended in the new update? That was a very helpful functionality :)

**Comment by john-friedman** [comment]
@dermonito Oops. Just patched this in v.302. Does it work for you now?

```
from datamule import Downloader

downloader = Downloader()
downloader.download(ticker=['AAPL','META'],form='10-K',output_dir='test1')
```

**Comment by dermonito** [comment]
@john-friedman Yes, it does, thank you!

**Comment by john-friedman** [comment]
Great!
